name: Build Test and Release

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  buildtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "VITE_APP_NAME=${{ secrets.VITE_APP_NAME }}" >> .env
          echo "VITE_API_ENDPOINT=${{ secrets.VITE_API_ENDPOINT }}" >> .env
          echo "VITE_LOGIN_TOKEN=${{ secrets.VITE_LOGIN_TOKEN }}" >> .env
          echo "VITE_USER_VALUE=${{ secrets.VITE_USER_VALUE }}" >> .env

      - name: Install dependencies
        run: cd client && npm install

      - name: Build
        run: cd client && npm run build

  build:
    name: Build and push release
    runs-on: ubuntu-latest
    needs: buildtest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}